profiles: dev-bak
logging:
  config: classpath:log4j2.xml
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/game_statstics?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
  jedis:
    host: 192.168.0.11
    port: 26379
    maxIdle: 10
    maxTotal: 100
    maxWaitMillis: 100000